### ISSUE TITLE
TextureVertex:1: error: 'non-opaque uniforms outside a block' : not allowed when using GLSL for Vulkan

### ISSUE THREAD

**Issue by AgnelSelvan** [bdero/flutter_gpu_shaders#1]
I tried to compile a texture fragment and vertex shader, by linking this shader file in `my_renderer.shaderbundle.json` and ran `dart run` command.

I got the following error
```
Unhandled exception:
Exception: Failed to build shader bundle: Compilation failed for bundled shader "TextureVertex".
TextureVertex: GLSL to SPIRV failed; Compilation error. 1 error(s) and 0 warning(s).
TextureVertex:1: error: 'non-opaque uniforms outside a block' : not allowed when using GLSL for Vulkan

#0      _buildShaderBundleJson (package:flutter_gpu_shaders/build.dart:43:5)
<asynchronous suspension>
#1      buildShaderBundleJson (package:flutter_gpu_shaders/build.dart:111:3)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///Users/a.selvan/Documents/flutter/my_3d_app/build.dart:17:5)
<asynchronous suspension>
#3      build (package:native_assets_cli/src/api/build.dart:94:3)
<asynchronous suspension>
#4      main (file:///Users/a.selvan/Documents/flutter/my_3d_app/build.dart:16:3)
<asynchronous suspension>
Building native assets for package:my_3d_app failed.
file:///Users/a.selvan/Documents/flutter/my_3d_app/build.dart returned with exit code: 255.
To reproduce run:
/Users/a.selvan/Documents/tools/flutter/bin/cache/dart-sdk/bin/dart --packages=/Users/a.selvan/Documents/flutter/my_3d_app/.dart_tool/package_config.json /Users/a.selvan/Documents/flutter/my_3d_app/.dart_tool/native_assets_builder/a1a53fb5edb6ac75812beaeba067f311/hook.dill --config=/Users/a.selvan/Documents/flutter/my_3d_app/.dart_tool/native_assets_builder/a1a53fb5edb6ac75812beaeba067f311/config.json
stderr:
Unhandled exception:
Exception: Failed to build shader bundle: Compilation failed for bundled shader "TextureVertex".
TextureVertex: GLSL to SPIRV failed; Compilation error. 1 error(s) and 0 warning(s).
TextureVertex:1: error: 'non-opaque uniforms outside a block' : not allowed when using GLSL for Vulkan

#0      _buildShaderBundleJson (package:flutter_gpu_shaders/build.dart:43:5)
<asynchronous suspension>
#1      buildShaderBundleJson (package:flutter_gpu_shaders/build.dart:111:3)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///Users/a.selvan/Documents/flutter/my_3d_app/build.dart:17:5)
<asynchronous suspension>
#3      build (package:native_assets_cli/src/api/build.dart:94:3)
<asynchronous suspension>
#4      main (file:///Users/a.selvan/Documents/flutter/my_3d_app/build.dart:16:3)
<asynchronous suspension>

stdout:
        
Error: Compiling native assets failed.
```

But please remember that I got this error when I tried to use texture on my shaders.

texture.frag

```
uniform sampler2D tex;

in vec2 v_texture_coords;
in vec4 v_color;
out vec4 frag_color;

void main() {
  frag_color = v_color * texture(tex, v_texture_coords);
}
```

texture.vert
```
uniform mat4 mvp;

in vec3 position;
in vec2 texture_coords;
in vec4 color;
out vec2 v_texture_coords;
out vec4 v_color;

void main() {
  v_texture_coords = texture_coords;
  v_color = color;
  gl_Position = mvp * vec4(position, 1.0);
}
```

**Comment by bdero** [comment]
Non-sampler uniforms need to be placed in a uniform block.

i.e.
```glsl
uniform FragInfo {
  mat4 mvp;
}
frag_info;
```

Then they can be referenced via the block: `frag_info.mvp`
