### ISSUE TITLE
Looks like `native_assets_cli: ^0.9.0` breaks `flutter_gpu_shaders`?

### ISSUE THREAD

**Issue by domesticmouse** [bdero/flutter_gpu_shaders#3]
```console
/Users/brettmorgan/.pub-cache/hosted/pub.dev/flutter_scene-0.5.0-0/hook/build.dart
stderr:
../../../../.pub-cache/hosted/pub.dev/flutter_gpu_shaders-0.1.3/lib/build.dart:86:14: Error: Type
'BuildOutput' not found.
    required BuildOutput buildOutput,
             ^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/flutter_gpu_shaders-0.1.3/lib/build.dart:86:14: Error:
'BuildOutput' isn't a type.
    required BuildOutput buildOutput,
             ^^^^^^^^^^^
Bad state: Generating kernel failed!
```

Example context: https://github.com/domesticmouse/my_first_triangle/actions/runs/11673905393/job/32505537185?pr=8

**Comment by mkustermann** [comment]
Yes, changing from`0.8.x` to `0.9.x` requires updating the code (generally speaking the semantic versioning convention is that from `0.X.Y` to `0.X+1.0` is breaking and may need to update the code)

(e.g. the `BuildOutput` is now `BuildOutputBuilder`)

**Comment by bdero** [comment]
The code break is not the only issue. The three build hooks that flutter_scene relies on (including this one) are hitting the same failure mode we saw for 0.9.0 in my assetless test: https://github.com/flutter/flutter/issues/158120#issuecomment-2456546207

```
Unhandled exception:
FormatException: No value was provided for required key: out_dir_shared
#0      MapJsonUtils.get (package:native_assets_cli/src/json_utils.dart:50:7)
#1      MapJsonUtils.path (package:native_assets_cli/src/json_utils.dart:25:48)
#2      new HookConfig (package:native_assets_cli/src/config.dart:88:38)
#3      new BuildConfig (package:native_assets_cli/src/config.dart)
#4      build (package:native_assets_cli/src/api/build.dart:99:18)
#5      main (file:///Users/bdero/projects/flutter/apps/flutter_scene/hook/build.dart:7:9)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Building native assets for package:flutter_scene failed.
file:///Users/bdero/projects/flutter/apps/flutter_scene/hook/build.dart returned with exit code: 255.
```

**Comment by bdero** [comment]
Continuing the discussion in https://github.com/dart-lang/native/issues/1698.

**Comment by bdero** [comment]
This is now fixed in new versions of flutter_gpu_shaders.
* 0.1.4 pins native_assets_cli to <0.9.0.
* 0.2.0 upgrades native_assets_cli to 0.9.0.

**Comment by mkustermann** [comment]
Thanks for confirming and apologies for the inconvenience, @bdero !
